Repository openshift-assisted/prow-jobs-scraper, pull requests merged in 2022-11, with the labels that each got.

#31 MGMT-11729: Retrieve equinix metadata from rehearse jobs
  .env
  src/prowjobsscraper/prowjob.py
  tests/prowjobsscraper/prowjob_assets/expected_prowjobs.json
  tests/prowjobsscraper/prowjob_assets/valid_prow_response.json
  tests/prowjobsscraper/test_prowjob.py
Labels: approved, size/M, lgtm

#34 NO-ISSUE: upgrade google storage
  Makefile
  pyproject.toml
Labels: approved, lgtm, size/S

#39 NO-ISSUE: fix permission issue with docker build
  Dockerfile
Labels: approved, lgtm, size/XS

#38 MGMT-12553: Adding an automated basic jobs analysis report (weekly at the moment)
  Dockerfile
  openshift/template.yaml
  pyproject.toml
  src/jobsautoreport/__init__.py
  src/jobsautoreport/config.py
  src/jobsautoreport/main.py
  src/jobsautoreport/query.py
  src/jobsautoreport/report.py
  src/jobsautoreport/utils.py
Labels: approved, lgtm, ok-to-test, size/L

#40 MGMT-12553: fixing spec.schedule error in integration
  openshift/template.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#41 test jobs-auto-report
  openshift/template.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#42 Expanding test cronjob interval
  openshift/template.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#44 MGMT-12553: Adjusting the index_name for queries
  src/jobsautoreport/main.py
Labels: approved, lgtm, size/XS, ok-to-test

#45 MGMT-12553: Switching querying method from 'search' to 'scan'
  src/jobsautoreport/query.py
  src/jobsautoreport/utils.py
Labels: approved, lgtm, size/S

#46 MGMT-12553: fixing some typos, changing the cronjob schedule back to 'weekly', formatting the average job duration to be composed of minutes, seconds
  openshift/template.yaml
  src/jobsautoreport/main.py
  src/jobsautoreport/query.py
  src/jobsautoreport/report.py
Labels: approved, size/M, lgtm

#48 MGMT-12553: Fixing the indentation of lines written to slack
  src/jobsautoreport/main.py
Labels: approved, lgtm, ok-to-test
