Repository openshift-assisted/prow-jobs-scraper, pull requests merged in 2023-09, with the labels that each got.

#236 MGMT-15741: Refactoring jobs-auto-report to make it more modular and well-suited for feature flags architecture
  openshift/template.yaml
  src/jobsautoreport/config.py
  src/jobsautoreport/consts.py
  src/jobsautoreport/main.py
  src/jobsautoreport/models.py
  src/jobsautoreport/plot.py
  src/jobsautoreport/report.py
  src/jobsautoreport/slack.py
  src/jobsautoreport/slack/__init__.py
  src/jobsautoreport/slack/slack_generate.py
  src/jobsautoreport/slack/slack_report.py
  src/jobsautoreport/trends.py
  tests/jobsautoreport/conftest.py
  tests/jobsautoreport/test_report.py
  tests/jobsautoreport/test_slack.py
  tests/jobsautoreport/test_slack_generate.py
  tests/jobsautoreport/test_slack_report.py
  tests/jobsautoreport/test_trends.py
Labels: approved, lgtm, size/XXL, jira/valid-reference

#238 NO-ISSUE: Fix boolean openshift parameters
  openshift/template.yaml
Labels: approved, lgtm, size/S, jira/valid-reference

#239 MGMT-15767: Fix scraper's usages gathering
  openshift/template.yaml
  src/prowjobsscraper/config.py
  src/prowjobsscraper/equinix_usages.py
  src/prowjobsscraper/main.py
Labels: approved, size/M, lgtm, jira/valid-reference

#240 NO-ISSUE: Fix Enum value in rehearse jobs
  src/jobsautoreport/report.py
Labels: approved, lgtm, size/XS, jira/valid-reference

#241 NO-ISSUE: Add logs for seeing raw report before sending to slack
  src/jobsautoreport/report.py
Labels: approved, lgtm, size/S, jira/valid-reference

#243 NO-ISSUE: Disable cost by job type
  src/jobsautoreport/slack/slack_report.py
  tests/jobsautoreport/test_slack_report.py
Labels: approved, size/M, lgtm, jira/valid-reference

#244 forbid concurrent execution to prevent errors piling up
  openshift/template.yaml
Labels: approved, lgtm, size/XS

#246 NO-ISSUE: Forbid concurrent execution of all cronjobs
  openshift/template.yaml
Labels: approved, lgtm, size/XS, jira/valid-reference

#247 MGMT-15872: Bump python version
  Dockerfile
  pyproject.toml
Labels: approved, lgtm, size/XS, jira/valid-reference
