Repository openshift-assisted/prow-jobs-scraper, pull requests merged in 2023-01, with the labels that each got.

#87 NO-ISSUE: changing the message format, adding debugging logs
  src/jobsautoreport/report.py
  src/jobsautoreport/slack.py
  tests/jobsautoreport/test_report.py
  tests/jobsautoreport/test_slack.py
Labels: approved, lgtm, size/L

#88 NO-ISSUE: Testing different time interval
  src/jobsautoreport/main.py
Labels: approved, lgtm, size/S

#90 NO-ISSUE: Use iso calendar to name ES indices
  pyproject.toml
  src/prowjobsscraper/event.py
  tests/prowjobsscraper/test_event.py
Labels: approved, size/M, lgtm

#92 NO-ISSUE: Changing the report structure so it will be one-threaded, changing the report to be 8AM UTC -> 8AM UTC
  src/jobsautoreport/main.py
  src/jobsautoreport/slack.py
  tests/jobsautoreport/test_slack.py
Labels: approved, size/M, lgtm

#93 NO-ISSUE: Changing the report time, making message clearer
  src/jobsautoreport/main.py
  src/jobsautoreport/slack.py
  tests/jobsautoreport/test_slack.py
Labels: approved, size/M, lgtm

#102 NO-ISSUE: Fixes and improvements
  src/jobsautoreport/report.py
  src/jobsautoreport/slack.py
  tests/jobsautoreport/test_report.py
  tests/jobsautoreport/test_slack.py
Labels: approved, lgtm, size/L

#107 NO-ISSUE: Omitting jobs with no failures from top failed jobs
  src/jobsautoreport/report.py
  tests/jobsautoreport/test_report.py
Labels: approved, lgtm, size/L, jira/valid-reference

#108 MGMT-13343: Adding postsubmit jobs to the report
  src/jobsautoreport/report.py
  src/jobsautoreport/slack.py
  tests/jobsautoreport/test_report.py
  tests/jobsautoreport/test_slack.py
Labels: approved, lgtm, size/L, jira/valid-reference

#109 NO-ISSUE: Add variant to slack name when necessary to avoid name collision
  src/jobsautoreport/report.py
  src/jobsautoreport/slack.py
  tests/jobsautoreport/test_report.py
  tests/jobsautoreport/test_slack.py
Labels: approved, lgtm, size/L, jira/valid-reference

#110 MGMT-13337: Adding monthly report
  openshift/template.yaml
  pyproject.toml
  src/jobsautoreport/config.py
  src/jobsautoreport/main.py
  src/jobsautoreport/models.py
Labels: approved, lgtm, size/L, jira/valid-reference

#113 NO-ISSUE: Add target to publish coverage to codecov
  Makefile
  hack/publish-codecov.sh
  pyproject.toml
Labels: approved, size/M, lgtm, jira/valid-reference
