Repository openshift-assisted/prow-jobs-scraper, pull requests merged in 2024-10, with the labels that each got.

#345 NO-ISSUE: Enable duplicates removal of latest index from index group
  openshift/template.yaml
  src/elasticsearch_cleanup/config.py
  src/elasticsearch_cleanup/main.py
  tests/elasticsearch_cleanup/test_main.py
Labels: approved, size/M, lgtm, jira/valid-reference

#344 MGMT-19125: Migrate prow-jobs-scraper to Konflux
  Dockerfile
  build_deploy.sh
Labels: approved, lgtm, size/S, ok-to-test, jira/valid-reference

#347 MGMT-19125: fix tekton pipeline on push
  .tekton/prow-jobs-scraper-saas-main-push.yaml
Labels: approved, lgtm, size/XS, ok-to-test, jira/valid-reference

#351 MGMT-19174: Add rpms-signature-scan to Konflux pipeline
  .tekton/prow-jobs-scraper-saas-main-pull-request.yaml
  .tekton/prow-jobs-scraper-saas-main-push.yaml
Labels: approved, size/M, lgtm, jira/valid-reference
